package com.order.enums;

public enum OrderStatus {

    PENDING,CREATED,PLACED,ACCEPTED,PREPARING,READY,PICKED_UP, DELIVERED,
    CANCELLED,ASSIGNED,EN_ROUTE_TO_PICKUP, EN_ROUTE_TO_DROPOFF,FAILED,
    REFUNDED, RETURNED, COMPLETED, DRAFT, PENDING_PAYMENT, RETURN_REQUESTED, SHIPPED
}
